config/routes.rb
Rails.application.routes.draw do

  root 'blocks#index'
  resources :block, :controller=>"blocks"
  resources :tx, :controller=>"txes"
  resources :addresses
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/address.rb
class Address < ApplicationRecord

  def self.generate_keys
    key = Bitcoin::generate_key
    {prvkey: key[0], pubkey: key[1]}
  end

  def pub_address
    Bitcoin::pubkey_to_address(self.pubkey)
  end

  def get_txes
    # tx1.showtx.outputs[0].parsed_script.get_address - чтобы узнать в каких транзакциях был адрес
    # tx1.showtx.outputs[0].value – чтобы посчитать суммы транзакций

    select = []
    Tx.all.map { |tx| tx.showtx.outputs.map{|output| select.push(tx) if output.parsed_script.get_address == self.pub_address } }
    select
  end

  def get_outputs
    outputs = []
    get_txes.map { |tx| tx.showtx.outputs.map{|out| outputs.push(out) if out.parsed_script.get_address == self.pub_address }}
    outputs
  end

  def get_value
    value = 0
    get_outputs.map { |output| value += output.value }
    value
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/block.rb
class Block < ApplicationRecord
  self.primary_key = 'blhash'
  has_many :txes, primary_key: :blhash

  def showbl
    Bitcoin::P::Block.from_hash(self.bldata)
  end

  def orphane?
    orphane=false
    self.bldata["tx"].map { |tx| Bitcoin::P::Tx.from_hash(tx,false).hash != tx["hash"]? orphane=true : nil }
    orphane
  end

  def total_value
    sum = 0
    self.showbl.tx.map { |tx| tx.outputs.map { |e| sum+=e.value } }
    sum
  end

  def set_relate_txs
    unless self.orphane?
      self.showbl.tx.map{ |tx|
        find_tx = Tx.where(txhash: tx.hash).take
        unless find_tx
          find_tx = Tx.new
          find_tx.txhash = tx.hash
          find_tx.txdata = tx.to_hash
          find_tx.save
        end
        self.txes << find_tx
      }
    end
  end

  def tx_hashes
    unless self.orphane?
      self.showbl.tx_hashes
    else
      self.bldata["tx"].map{|tx|tx["hash"]}
    end
  end

  def tx_hash_at_this_block?(txhash)
    self.bldata["tx"].map{|tx|tx["hash"]}.include?(txhash)
  end

  def self.get_by_tx_hash(txhash)
    Block.where("'{\"hash\": \"#{txhash}\" }' <@ ANY (ARRAY(select jsonb_array_elements(bldata -> 'tx')))")
  end
end

app/models/tx.rb
class Tx < ApplicationRecord
  self.primary_key = 'txhash'
  belongs_to :block, optional: true, autosave: true
  def showtx
    Bitcoin::P::Tx.from_hash(self.txdata)
  end


end

app/controllers/addresses_controller.rb
class AddressesController < ApplicationController
  before_action :set_address, only: [:show, :destroy]

  # GET /addresses
  # GET /addresses.json
  def index
    @addresses = Address.all
  end

  # GET /addresses/1
  # GET /addresses/1.json
  def show
  end

  # GET /addresses/new
  def new
    @address = Address.new
  end

  # GET /addresses/1/edit
  # def edit
  # end

  # POST /addresses
  # POST /addresses.json
  def create
    @address = Address.new(Address.generate_keys)

    respond_to do |format|
      if @address.save
        format.html { redirect_to @address, notice: 'Address was successfully created.' }
        format.json { render :show, status: :created, location: @address }
      else
        format.html { render :new }
        format.json { render json: @address.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /addresses/1
  # PATCH/PUT /addresses/1.json
    # def update
    #   respond_to do |format|
    #     if @address.update(address_params)
    #       format.html { redirect_to @address, notice: 'Address was successfully updated.' }
    #       format.json { render :show, status: :ok, location: @address }
    #     else
    #       format.html { render :edit }
    #       format.json { render json: @address.errors, status: :unprocessable_entity }
    #     end
    #   end
    # end

  # DELETE /addresses/1
  # DELETE /addresses/1.json
  def destroy
    @address.destroy
    respond_to do |format|
      format.html { redirect_to addresses_url, notice: 'Address was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_address
      @address = Address.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def address_params
      params.require(:address)#.permit(:prvkey, :pubkey)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/blocks_controller.rb
class BlocksController < ApplicationController
  before_action :set_block, only: [:show, :edit, :update, :destroy]

  # GET /blocks
  # GET /blocks.json
  def index
    @blocks = Block.all
  end

  # GET /blocks/1
  # GET /blocks/1.json
  def show
  end

  # GET /blocks/new
  def new
    @block = Block.new
  end

  # GET /blocks/1/edit
  def edit
  end

  # POST /blocks
  # POST /blocks.json
  def create
    @block = Block.new(block_params)

    respond_to do |format|
      if @block.save
        format.html { redirect_to @block, notice: 'Block was successfully created.' }
        format.json { render :show, status: :created, location: @block }
      else
        format.html { render :new }
        format.json { render json: @block.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /blocks/1
  # PATCH/PUT /blocks/1.json
  def update
    respond_to do |format|
      if @block.update(block_params)
        format.html { redirect_to @block, notice: 'Block was successfully updated.' }
        format.json { render :show, status: :ok, location: @block }
      else
        format.html { render :edit }
        format.json { render json: @block.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /blocks/1
  # DELETE /blocks/1.json
  def destroy
    @block.destroy
    respond_to do |format|
      format.html { redirect_to blocks_url, notice: 'Block was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_block
      @block = Block.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def block_params
      params.require(:block).permit(:blhash, :bldata)
    end
end

app/controllers/txes_controller.rb
class TxesController < ApplicationController
  before_action :set_tx, only: [:show, :edit, :update, :destroy]

  # GET /txes
  # GET /txes.json
  def index
    @txes = Tx.all
  end

  # GET /txes/1
  # GET /txes/1.json
  def show
  end

  # GET /txes/new
  def new
    @tx = Tx.new
  end

  # GET /txes/1/edit
  def edit
  end

  # POST /txes
  # POST /txes.json
  def create
    @tx = Tx.new(tx_params)

    respond_to do |format|
      if @tx.save
        format.html { redirect_to @tx, notice: 'Tx was successfully created.' }
        format.json { render :show, status: :created, location: @tx }
      else
        format.html { render :new }
        format.json { render json: @tx.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /txes/1
  # PATCH/PUT /txes/1.json
  def update
    respond_to do |format|
      if @tx.update(tx_params)
        format.html { redirect_to @tx, notice: 'Tx was successfully updated.' }
        format.json { render :show, status: :ok, location: @tx }
      else
        format.html { render :edit }
        format.json { render json: @tx.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /txes/1
  # DELETE /txes/1.json
  def destroy
    @tx.destroy
    respond_to do |format|
      format.html { redirect_to txes_url, notice: 'Tx was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_tx
      @tx = Tx.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def tx_params
      params.require(:tx).permit(:txhash, :txdata)
    end
end

app/helpers/addresses_helper.rb
module AddressesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/blocks_helper.rb
module BlocksHelper
end

app/helpers/txes_helper.rb
module TxesHelper
end

app/views/addresses/_form.html.erb
<%= form_for(address) do |f| %>
  <% if address.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(address.errors.count, "error") %> prohibited this address from being saved:</h2>

      <ul>
      <% address.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/addresses/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Addresses</h1>

<table>
  <thead>
    <tr>
      <th>Pub address</th>
  
    </tr>
  </thead>

  <tbody>
    <% @addresses.each do |address| %>
      <tr>
        <td><%= link_to address.pub_address, address %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Generate New Address', new_address_path %>

app/views/addresses/new.html.erb
<h1>New Address</h1>

<%= render 'form', address: @address %>

<%= link_to 'Back', addresses_path %>

app/views/addresses/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Pub address:</strong>
  <%= @address.pub_address %>
</p>
<p>
  <strong>Balance:</strong>
  <%= @address.get_value.to_f/100000000 %> BTC
</p>

<%= link_to 'Back', addresses_path %>

app/views/blocks/_form.html.erb
<%= form_for(block) do |f| %>
  <% if block.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(block.errors.count, "error") %> prohibited this block from being saved:</h2>

      <ul>
      <% block.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :blhash %>
    <%= f.text_field :blhash %>
  </div>

  <div class="field">
    <%= f.label :bldata %>
    <%= f.text_field :bldata %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/blocks/edit.html.erb
<h1>Editing Block</h1>

<%= render 'form', block: @block %>

<%= link_to 'Show', @block %> |
<%= link_to 'Back', blocks_path %>

app/views/blocks/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Recent Blocks</h1>

<table>
  <thead>
    <tr>
      <th>Height</th>
      <th>Hash</th>
      <th>Time</th>
      <th>TX</th>
      <th>Size</th>
      <th>Total</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @blocks.each do |block| %>
      <tr>
        <% if block.orphane? %>
          <td><%= link_to "[ ORPHANE! ]", block %></td>
          <td><%= link_to block.blhash, block  %></td>
          <td><%= Time.at(block.bldata["time"]) %></td>
          <td><%= block.bldata["tx"].count %></td>
          <td><%= block.bldata["size"] %></td>
          <td><%= 0 %> BTC </td>
        <% else %>
          <td><%= link_to block.showbl.bip34_block_height, block %></td>
          <td><%= link_to block.blhash, block  %></td>
          <td><%= Time.at(block.showbl.time) %></td>
          <td><%= block.showbl.tx.count %></td>
          <td><%= block.bldata["size"] %></td>
          <td><%= block.total_value.to_f/100000000 %> BTC </td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/blocks/new.html.erb
<h1>New Block</h1>

<%= render 'form', block: @block %>

<%= link_to 'Back', blocks_path %>

app/views/blocks/show.html.erb
<p>
  <h1>Bitcoin - Block Details</h1>
</p>
<p id="notice"><%= notice %></p>

<p>
  <strong>Hash:</strong>
  <%= @block.blhash %>
</p>

<p>
  <strong>Height:</strong>
  <%= @block.showbl.bip34_block_height %>
</p>

<p>
  <strong>Time:</strong>
  <%= Time.at(@block.showbl.time) %>
</p>

<p>
  <strong>Transactions:</strong>
  <%= @block.showbl.tx.size %>
</p>

<p>
  <strong>Size:</strong>
  <%= @block.bldata["size"] %> Bytes
</p>

<p>
  <strong>Total Value:</strong>
  <%= @block.total_value %> BTC
</p>

<%= link_to 'Back', block_index_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bitupper</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>

    <p>
      <%= link_to 'Recent Blocks', block_index_path %>
      <%= link_to 'Recent Tx', tx_index_path %>
      <%= link_to 'Addresses', addresses_path %>
    </p>
  </body>
</html>

app/views/txes/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Transactions</h1>

<table>
  <thead>
    <tr>
      <th>Hash</th>
    </tr>
  </thead>

  <tbody>
    <% @txes.each do |tx| %>
      <tr>
        <td><%= link_to tx.txhash, tx %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/txes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Hash:</strong>
  <%= @tx.txhash %>
</p>

<p>
  <strong>Bitcoin::Protocol::Tx:</strong>
  <%= @tx.showtx.to_hash %>
</p>

<%= link_to 'back', tx_index_path %>